spring.application.name=biblioteca-api
spring.data.mongodb.uri=mongodb+srv://adminBiblioteca:Biblio2026
cluster.mongodb.net/biblioteca_db?retryWrites=true&w=majority
spring.data.mongodb.database=biblioteca_db
server.port=8080