spring.application.name=biblioteca-api
spring.mongodb.uri=mongodb+srv://adminBiblioteca:Biblio2026@cluster0.cdkrvue.mongodb.net/biblioteca_db?appName=Cluster0
spring.mongodb.database=biblioteca_db
server.port=8080